mysite/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    path('getTask/<int:gameid>/<str:location>/<int:tag>', views.getTask, name='getTask'),
    path('submitTask/<int:gameid>/<int:taskid>', views.submitTask, name='submitTask'),
    path('signin', views.signin, name='signin'),
    path('new_account', views.new_account, name='new_account'),
    path('signout', views.signout, name='signout')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/',include('chat.urls'))
]

mysite/chat/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    # Task model
    # core info
    doneness = models.IntegerField() # one for done 0 for not done
    type = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    note = models.CharField(max_length=500)
    # codes foe each stage of the task
    codefinal = models.CharField(max_length=200, default='', blank=True)
    code1 = models.CharField(max_length=200, default='', blank=True)
    code2 = models.CharField(max_length=200, default='', blank=True)
    # locations of each stage
    location1 = models.CharField(max_length=200, default='', blank=True)
    location2 = models.CharField(max_length=200, default='', blank=True)
    location3 = models.CharField(max_length=200, default='', blank=True)

    def __str__(self):
        return self.name

class Player(models.Model):
    # player in a game
    name = models.CharField(max_length=200) # this is the same as the user name
    aliveness = models.IntegerField() # 1 for alove 0 for dead
    tag = models.IntegerField() # a random code needed to kill someone
    tasks = models.ManyToManyField(Task)
    role = models.CharField(max_length=200) # what role the user is default is un
    votes = models.IntegerField() # how many votes they have recieved in a meating
    voted = models.IntegerField() # wether or not they have voted

    def __str__(self):
        return self.name

class Game(models.Model):
    # a game
    gameId = models.IntegerField() # the noom number
    status = models.CharField(max_length=200) # wat stage the game is in
    tasks = models.ManyToManyField(Task)
    players = models.ManyToManyField(Player)
    auth = models.CharField(max_length=200, default='', blank=True) # an optional auth code for authorised task compleation

    def __str__(self):
        return str(self.gameId)

mysite/minigames/models.py
from django.db import models

# Create your models here.

mysite/chat/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from .models import *
# Create your views here.


def index(request): # index
    context = {"additional_context": {'a': 'chat'}}
    return render(request, 'chat/index.html', context)

def room(request, room_name): # room view
    start = 0
    # if there isnt already a game with this room num a game will be created
    if len(Game.objects.filter(gameId=room_name)) == 0:
        game = Game(gameId=room_name, status='lobby')
        game.save()
        start = 1

    context = {"additional_context": {'a': 'chat'}, 'room_name': room_name, 'start': start}
    return render(request, 'chat/room.html', context)

def submitTask(request, gameid, taskid,  auth=''):
    game = Game.objects.filter(gameId=gameid)[0]
    # used by the tasks to submit a compleated task
    task = Task.objects.get(id=taskid)

    # checks if the right authorisation is used
    if game.auth == auth:
        # changes the level the task is on
        task.doneness -= 1
        task.save()
        response = {'status': 1}
    else:
        response = {'status': 0}

    return JsonResponse(data=response) # responds with wether or not the right codes have been entered

def getTask(request, gameid, location, tag, auth=''):
    # used to sign users in and give them thr right task
    game = Game.objects.filter(gameId=gameid)[0]
    try:
        tasks = game.players.filter(tag=tag)[0].tasks.all()
    except:
        return JsonResponse(data={'status': 'playerNA'})

    # find a task at this location
    if len(game.tasks.filter(type='sabotage')) != 0:
        tasks = game.tasks.filter(type='sabotage')

        if len(tasks.filter(location1=location).filter(doneness=1)) > 0:
            task = tasks.filter(location1=location).filter(doneness=1)[0]
        elif len(tasks.filter(location2=location).filter(doneness=2)) > 0:
            task = tasks.filter(location2=location).filter(doneness=2)[0]
        elif len(tasks.filter(location3=location).filter(doneness=3)) > 0:
            task = tasks.filter(location3=location).filter(doneness=3)[0]
        else:
            return JsonResponse(data={'status': 'sabotage'})
    else:
        if len(tasks.filter(location1=location).filter(doneness=1)) > 0:
            task = tasks.filter(location1=location).filter(doneness=1)[0]
        elif len(tasks.filter(location2=location).filter(doneness=2)) > 0:
            task = tasks.filter(location2=location).filter(doneness=2)[0]
        elif len(tasks.filter(location3=location).filter(doneness=3)) > 0:
            task = tasks.filter(location3=location).filter(doneness=3)[0]
        else:
            return JsonResponse(data={'status': 'locationNA'})

    response = {
        'status': 'sucsess',
        'taskid': task.id,
        'level': task.doneness,
        'name': task.name
    }
    return JsonResponse(data=response) # responds with wether or not the right codes have been entered



def signin(request): # sign in function this shit is well writen so im not going to bother commenting
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('chat:index')
        else:
            context = {'error_message': 'could not authentecate account'}
            return render(request, 'chat/signin.html', context)

    elif request.method == 'GET':
        return render(request, 'chat/signin.html')


def new_account(request): # creates a new user function this shit is well writen so im not going to bother commenting

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        try:
            new_user = User(username=username, email=email)
            new_user.set_password(password)
            new_user.save()

            context = 'sucsessfuly created new account'
            return redirect('chat:index', error=context)
        except:
            context = {'error_message': 'could not created new account'}
            return render(request, 'chat/new_account.html', context)

    elif request.method == 'GET':
        return render(request, 'chat/new_account.html')


def signout(request):
    logout(request)
    return redirect('chat:index')

mysite/minigames/views.py
from django.shortcuts import render

# Create your views here.

mysite/chat/templates/chat/index.html
{% extends 'base.html' %}

{% block content %}
<div class="fluid-container">

    <div class="p-3 jumbotron mx-auto" style="width: 50%;">
      <h2>Chat rooms</h2>
      <p>You can join chat rooms by entering the chat romm id or by selecting one of the chat rooms below</p>
    </div>


    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="card mx-auto" style="width: 50%;">
      <div class="card-header">
        <h2>What chat room would you like to enter?</h2>
      </div>
      <div class="card-body">


        <input class="form-group" id="room-name-input" type="text" size="100" placeholder="ID"><br>
        <input class='btn btn-success' id="room-name-submit" type="button" value="Enter">

        <script>
            document.querySelector('#room-name-input').focus();
            document.querySelector('#room-name-input').onkeyup = function(e) {
                if (e.keyCode === 13) {  // enter, return
                    document.querySelector('#room-name-submit').click();
                }
            };

            document.querySelector('#room-name-submit').onclick = function(e) {
                var roomName = document.querySelector('#room-name-input').value;
                window.location.pathname = '/chat/' + roomName + '/';
            };
        </script>

      </div>
    </div>

</div>
{% endblock %}

mysite/chat/templates/chat/new_account.html
{% extends 'base.html' %}

{% block content %}
<div class="fluid-container">
<div class="">
  <div class="col px-md-5">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="card">
      <div class="card-header">
        <h2>Create Account</h2>
      </div>
      <div class="card-body">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form class="create" action="{% url 'chat:new_account' %}" method="post">
          {% csrf_token %}

          <div class="form-group">
            <label for="question_name">Username</label><br>
            <input type="text" name="username" id="username" placeholder="username" required><br>
          </div>

          <div class="form-group">
            <label for="email">Email</label><br>
            <input type="text" name="email" id="email" placeholder="example@example.com" required><br>
          </div>

          <div class="form-group">
            <label for="option">Password</label><br>
            <input type="text" id="password" name="password" placeholder="strong password" required><br>
          </div>

          <input class='btn btn-success' type="submit" value="Create">

        </form>
      </div>
    </div>


  </div>
</div>
</div>
{% endblock %}

mysite/chat/templates/chat/signin.html
{% extends 'base.html' %}

{% block content %}
<div class="fluid-container">
<div class="">
  <div class="col px-md-5">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="card">
      <div class="card-header">
        <h2>Login</h2>
      </div>
      <div class="card-body">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form class="create" action="{% url 'chat:signin' %}" method="post">
          {% csrf_token %}

          <div class="form-group">
            <label for="question_name">Username</label><br>
            <input type="text" name="username" id="username" placeholder="username" required><br>
          </div>

          <div class="form-group">
            <label for="option">Password</label><br>
            <input type="password" id="password" name="password" placeholder="password" required><br>
          </div>

          <input class='btn btn-success' type="submit" value="signin">

        </form>
      </div>
    </div>


  </div>
</div>
</div>
{% endblock %}

mysite/chat/templates/chat/task.html
{% extends 'base.html' %}

{% block content %}
<div class="fluid-container">
<div class="">
  <div class="col px-md-5">
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="card">
      <div class="card-header">
        <h2>Login to reserch computer</h2>
      </div>
      <div class="card-body">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form class="create" action="{% url 'chat:getTask' %}" method="post">
          {% csrf_token %}

          <div class="form-group">
            <label for="question_name">Username</label><br>
            <input type="text" name="username" id="username" placeholder="username" required><br>
          </div>

          <div class="form-group">
            <label for="option">Tag</label><br>
            <input type="Tag" id="Tag" name="Tag" placeholder="Tag" required><br>
          </div>

          <input class='btn btn-success' type="submit" value="signin">

        </form>
      </div>
    </div>


  </div>
</div>
</div>
{% endblock %}

mysite/common-static/templates/base.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<meta name="viewport" content="width=device-width, initial-scale=1.0">


<head>
  <title>Ben Comunication</title>
</head>

<body class="">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-3">
    <div class="container-fluid">
        <a href="#" class="navbar-brand mr-3">Comunication</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">

              <!-- urls for the nav bar -->
              <a href="{% url 'chat:index' %}" class="nav-item nav-link {% if additional_context.a == 'chat' %} active {% endif %}">Chat</a>

              <div class="navbar-nav ml-auto ">
              {% if request.user.is_authenticated %}
                <a href="{% url 'chat:signout' %}" class="nav-item btn btn-secondary m-1">Signout of {{ request.user }}</a>
              {% else %}
              <div class="m-1">
                <a class="btn btn-success " href="{% url 'chat:signin' %}">Signin</a>
                <a class="btn btn-secondary" href="{% url 'chat:new_account' %}">Create Acount</a>
              </div>
              {% endif %}
              </div>

            </div>
        </div>
    </div>
  </nav>




  {% block content %}{% endblock %}

  <br><br><br>
  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Ben Ryc</p>
    </div>
    <!-- /.container -->
  </footer>

</body>

<!-- https://startbootstrap.com/templates/ -->